name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_pref_annotation:
    path: ../shared_pref_annotation

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.2
<<<<<<< HEAD
  dart_agnan:
    path: ../dart_agnan
=======
  athos:
    path: ../athos
  shared_pref_generator:
    path: ../shared_pref_generator
>>>>>>> fe734c2668ad7b8fe9b11a4e0e398b5a2ec8e0cf


flutter:
  uses-material-design: true