targets:
  $default:
    builders:
      shared_pref_generator|shared_pref_annotation:
        enabled: true

builders:
  shared_preferences_generator:
    target: ":shared_pref_generator"
    import: "package:shared_pref_generator/generator/preferences.dart"
    builder_factories: ["sharedPreferencesGenerator"]
    build_extensions: {".dart": [".shared_preferences_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  reactive_shared_preferences_generator:
    target: ":shared_pref_generator"
    import: "package:shared_pref_generator/generator/reactive_preferences.dart"
    builder_factories: ["reactiveSharedPreferencesGenerator"]
    build_extensions: {".dart": [".reactive_shared_preferences_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]