name: pref_gen
description: A new Flutter package.
version: 0.0.1
author: Gregory Sech
homepage: https://github.com/GregorySech/pref_gen

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  build: ^1.0.2
  source_gen: ^0.9.2
  code_builder: ^3.1.3
  pref_gen_annotations:
    path: ../pref_gen_annotations

dev_dependencies:
  build_runner: ^1.1.2
  
