name: athos
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  shared_preferences: ^0.4.3
  shared_pref_annotation:
    path: ../shared_pref_annotation
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.athos
    pluginClass: AthosPlugin
